spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_erudio
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
springdoc:
  pathsToMatch: /api/**/v1/**
  swagger-ui:
    use-root-path: true